### ISSUE TITLE
Default PROMPT doesn't look pretty on usage of zle-line-init

### ISSUE THREAD

**Issue by Felixoid** [woefe/git-prompt.zsh#11]
Hello. I set my PS only in `zle-line-init zle-keymap-select`, that means `$PROMPT` doesn't contain `gitprompt` on the start of the shell. Then I have annoying blinking of prompt

[![asciicast](https://asciinema.org/a/1JYdUOBvVNDcSBJXWCG0TbO2s.svg)](https://asciinema.org/a/1JYdUOBvVNDcSBJXWCG0TbO2s)

It was changed in https://github.com/woefe/git-prompt.zsh/commit/7dfff14efa11ac49332cada4f5837ab658281c94

**Comment by woefe** [comment]
I am pretty sure the flickering also happens if the git-prompt.zsh is not loaded, because zsh sets the prompt to `%m%#`, if you do not set it yourself (and you set it too late; in zle-line-init). I think the issue is therefore not related to my prompt.

Try recording another cast without my git-prompt loaded and then step through the recording step by step and you will see a short `ig-fel%`.

**Comment by woefe** [comment]
I've done some trouble shooting on your prompt. I've moved a lot of stuff out of the `zle-line-init` and `zle-keymap-select`. Everything inside these functions will be executed everytime a new prompt is shown or  when you change vi mode. But most variables never change (e.g. user, ssh). When you ssh into another machine or change user, you also get a new shell. So there is no need to update this with every new prompt.

The following patch is made on de64724 of your dotfiles. 
[patch.txt](https://github.com/woefe/git-prompt.zsh/files/3263180/patch.txt)

I hope that fixes it.

**Comment by Felixoid** [comment]
Hello Wolfgang.

Sorry for a long silence. Thank you very much for your patch. It fits almost perfect. The only thing which I've changed is `setopt PROMPT_SUBST`, it should be applied independently because of _PROMPT_VI and _PROMPT_VENV.

Best regards.
