### ISSUE TITLE
Space in prompt

### ISSUE THREAD

**Issue by Felixoid** [woefe/git-prompt.zsh#37]
Hello. Can you consider an option to disable the space at the end of the prompt?

**Comment by woefe** [comment]
It is possible to override PROMPT and remove the trailing space. Take a look at the examples. Remove the space for example from https://github.com/woefe/git-prompt.zsh/blob/55f40bdfb287122ea50c1c01ef056ca7dac175e5/examples/default.zsh#L24

Otherwise `PROMPT=${PROMPT% }` in your zshrc (after loading the git prompt) might work as a somewhat hacky workaround.
