### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by Felixoid** [woefe/git-prompt.zsh#38]
Hello. It looks like it is worth spinning a new release, there's been some useful changes since [2.3.0](https://github.com/woefe/git-prompt.zsh/compare/v2.3.0...master)

**Comment by woefe** [comment]
:+1:  

after #41 is merged

**Comment by telemachus** [comment]
One other random thought: `git status` can take a ` --no-optional-locks` flag, and I wonder if that's better, worse, any different than prepending the command with [`GIT_OPTIONAL_LOCKS=0`](https://github.com/woefe/git-prompt.zsh/blob/master/git-prompt.zsh#L78). (The `--no-optional-locks` seems to have been [available since 2017](https://github.com/git/git/commit/e6bf6afe27d9a600963e8733ce17e7b067a4701c) so it shouldn't be a problem in terms of different versions of git.)

Sorry if this isn't the best place to put this note, but I figure it may make sense to do before a new release.

**Comment by woefe** [comment]
Setting the env var is backwards compatible, hence I won't change it for the next release. I've added a TODO item for #42 to replace it with the command option once we require a newer Git version anyways.

**Comment by telemachus** [comment]
> 👍
> 
> after #41 is merged

Just to make everything up to date, this should now track #43.

**Comment by woefe** [comment]
https://github.com/woefe/git-prompt.zsh/releases/tag/v2.4.0
