### ISSUE TITLE
[Feature] Status of the current process

### ISSUE THREAD

**Issue by Felixoid** [woefe/git-prompt.zsh#44]
Hey-hey!

Just got a cool idea out of Julia Evans' post here https://social.jvns.ca/@b0rk/112146005917986039

![image](https://github.com/woefe/git-prompt.zsh/assets/3025537/527f5efe-b3e9-42ae-b4b0-0660a5ceefa7)

It would be useful to include the current stage of rebasing, merging, and so on processes in the prompt.

**Comment by Felixoid** [comment]
Here's idea of how it's implemented in the git itself: https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh#L527 + search for `/  r="/` in the code above

**Comment by woefe** [comment]
Thanks for the idea. I think this is not so straightforward to implement, because the currently ongoing operation is not available on `git status` porcelain output. I'd probably have to port and maintain the shell implementation you linked above, which I don't want to do.

For my own use I don't really miss the feature (except the rebase counter would be nice to have sometimes). I rarely leave the repo with an ongoing rebase/merge/etc. And while I am rebasing/merging/etc I know that I'm doing that, so no reminder in the prompt needed for my use-cases.

Sorry to close this for now. I'll consider re-opening it, if the information becomes available on the `git status` output.

**Comment by Felixoid** [comment]
Understandable. Maybe, some plugin system? Like, hooks to add our own output?
